== Deploying FrontLine on Kubernetes

If you're using Kubernetes-based injector pools, it is recommended to run FrontLine itself inside Kubernetes too:

* Less configuration is required than when connecting to a cluster from the outside
* It is not necessary to open firewall rules so that FrontLine can contact injectors

=== Getting FrontLine's Docker image

FrontLine's image is hosted as a private image on https://hub.docker.com/r/gatlingcorp/frontline[Docker Hub].

Please contact our support and provide us with your Docker Hub username so we can grant you access.

=== Getting FrontLine's injectors Docker image

FrontLine's injector image is publicly accessible on https://hub.docker.com/r/gatlingcorp/frontline-injector[Docker Hub].

=== Setup Cassandra

This manifest setups a single-node Cassandra cluster, along with a service to expose it

.kubernetes-cassandra.yml
[source,yaml]
----
include::includes/kubernetes-cassandra.yml[]
----

=== Setup FrontLine

==== Setup RBAC (optional)

If your cluster has RBAC enabled, this manifest configure the necessary permissions for FrontLine:

[source, yaml]
----
include::../commons/kubernetes-frontline-sa.yml[]
----

==== Setup Docker Hub credentials as a secret (Optional)

If you're not mirroring FrontLine's image in your private registry, you'll need to setup your Docker credentials as a secret to pull FrontLine's image:

----
kubectl create secret docker-registry docker-hub-credentials \
  --docker-server=<your-registry-server> \
  --docker-username=<your-name> \
  --docker-password=<your-pword> \
  --docker-email=<your-email>
----

==== Setup FrontLine

This manifest sets up FrontLine, pre configured with your license key and admin credentials.
You can then expose FrontLine using LoadBalancer/NodePort services, Ingress, etc...

.kubernetes-frontline.yml
[source, yaml]
----
include::includes/kubernetes-frontline.yml
----

NOTE: Depending on your needs, you may need to configure additional volumes on the FrontLine container (SSL certificate if HTTPS is configured, or keystore/truststore for LDAP support)
